# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartupDialog(object):
    def setupUi(self, StartupDialog):
        StartupDialog.setObjectName("StartupDialog")
        StartupDialog.resize(600, 134)
        StartupDialog.setMinimumSize(QtCore.QSize(414, 134))
        StartupDialog.setMaximumSize(QtCore.QSize(600, 134))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/ML.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StartupDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartupDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(StartupDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(StartupDialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(StartupDialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(StartupDialog)
        QtCore.QMetaObject.connectSlotsByName(StartupDialog)

    def retranslateUi(self, StartupDialog):
        _translate = QtCore.QCoreApplication.translate
        StartupDialog.setWindowTitle(_translate("StartupDialog", "Open"))
        self.label.setText(_translate("StartupDialog", "Add *.csv file to start working on your Project"))
        self.pushButton.setText(_translate("StartupDialog", "Ok"))
        self.pushButton_2.setText(_translate("StartupDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartupDialog = QtWidgets.QDialog()
    ui = Ui_StartupDialog()
    ui.setupUi(StartupDialog)
    StartupDialog.show()
    sys.exit(app.exec_())
